import manifest from "@/content/media-manifest.json";
import type { MediaAsset, MediaRef } from "./types";

/**
 * Generated by `scripts/process-media.mjs` from the client's raw photography.
 * Content references images by slug so renditions can be regenerated without
 * touching a single content file.
 */
export const mediaManifest = manifest as unknown as Record<string, MediaAsset>;

/**
 * Public prefix the site is served under. Empty for a root deployment; set to
 * the repository name for a GitHub Pages project site.
 */
export const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

/**
 * Prefixes a public-directory path with the base path.
 *
 * `next/image` normally applies the base path itself, but not when
 * `unoptimized` is set — the loader then returns `src` untouched. Without this,
 * every photograph 404s on a project-site deployment.
 *
 * Only for URLs that go into the DOM. Absolute URLs for metadata are built by
 * `absoluteUrl()` in lib/seo, which prefixes the full origin instead.
 */
export function assetPath(src: string): string {
  if (!src || !BASE_PATH) return src;
  if (src.startsWith("http") || src.startsWith("data:")) return src;
  return `${BASE_PATH}${src}`;
}

/** A visibly wrong placeholder — if this ever renders, a content slug is broken. */
const MISSING: MediaAsset = {
  slug: "missing",
  title: "Missing image",
  alt: "",
  tags: [],
  src: "",
  widths: [],
  width: 16,
  height: 9,
  aspect: 16 / 9,
  blurDataURL: "",
};

export function getMedia(ref: MediaRef | undefined | null): MediaAsset {
  if (!ref) return MISSING;
  return mediaManifest[ref] ?? MISSING;
}

export function getMediaList(refs: MediaRef[] | undefined | null): MediaAsset[] {
  if (!refs?.length) return [];
  return refs.map(getMedia).filter((m) => m.src);
}

export function hasMedia(ref: MediaRef | undefined | null): boolean {
  return Boolean(ref && mediaManifest[ref]);
}

/**
 * srcSet across the renditions actually generated for this image, so the
 * browser never downloads a width that does not exist.
 */
export function buildSrcSet(asset: MediaAsset): string {
  return asset.widths
    .map((w) => `/media/${asset.slug}-${w}.webp ${w}w`)
    .join(", ");
}

export const allMedia = Object.values(mediaManifest);
